- name: Configurar entorno basico con Nginx
  hosts: localhost
  become: yes 
  tasks: 
    - name: Actualizar la lista de paquetes
      apt:
        update_cache: yes
    
    - name: Instalar Nginx
      apt:
        name: nginx
        state: present
    
    - name: Iniciar y habilitar el servicio Nginx
      service:
        name: nginx
        state: started
        enabled: yes